jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Create backup tag before translation
        run: |
          ts=$(date +'%Y%m%d-%H%M%S')
          git tag backup-$ts
          git push origin backup-$ts

      - name: Restore & Build
        ...

      - name: Run ResxAutoTranslate
        ...

      - name: Commit changes
        ...

      - name: Push changes
        ...
